"use client";
import { useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, Bell, Camera, CheckCircle2, CircleDollarSign, CreditCard, FileSpreadsheet, Goal, Home, Landmark, LoaderCircle, Menu, MoreHorizontal, PiggyBank, Plus, ReceiptText, Search, Settings, TrendingUp, WalletCards, X } from "lucide-react";
import ModuleView from "@/components/module-view";

export type Tx={id:number;title:string;category:string;date:string;amount:number;kind:"income"|"expense"};
const seed:Tx[]=[
 {id:1,title:"เงินเดือน",category:"รายรับ",date:"15 ก.ย. 2569",amount:58000,kind:"income"},
 {id:2,title:"ค่าเช่าบ้าน",category:"ที่อยู่อาศัย",date:"14 ก.ย. 2569",amount:-12500,kind:"expense"},
 {id:3,title:"Central Food Hall",category:"อาหาร",date:"13 ก.ย. 2569",amount:-1842,kind:"expense"},
 {id:4,title:"ลงทุน DCA",category:"การลงทุน",date:"12 ก.ย. 2569",amount:-5000,kind:"expense"},
 {id:5,title:"ค่าน้ำมัน",category:"เดินทาง",date:"11 ก.ย. 2569",amount:-1260,kind:"expense"},
];
const nav=[[Home,"ภาพรวม"],[ReceiptText,"รายการเงิน"],[WalletCards,"บัญชี"],[CreditCard,"บัตรและหนี้"],[Goal,"งบประมาณ"],[PiggyBank,"เงินออม"],[TrendingUp,"การลงทุน"],[Landmark,"ภาษี"]] as const;
const baht=(n:number)=>new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",maximumFractionDigits:0}).format(Math.abs(n));

export default function HomePage(){
 const [txs,setTxs]=useState(seed),[active,setActive]=useState("ภาพรวม"),[drawer,setDrawer]=useState(false);
 const [modal,setModal]=useState<"add"|"import"|"receipt"|"summary"|null>(null),[notice,setNotice]=useState("");
 const [processing,setProcessing]=useState(false),[progress,setProgress]=useState(0);
 const [summary,setSummary]=useState({files:0,rows:0,income:0,expense:0,duplicates:0,source:""});
 const [draft,setDraft]=useState({title:"",amount:"",kind:"expense" as "income"|"expense",category:"อาหาร"});
 const csv=useRef<HTMLInputElement>(null),receipt=useRef<HTMLInputElement>(null);
 const totals=useMemo(()=>({income:txs.filter(x=>x.kind==="income").reduce((s,x)=>s+x.amount,0),expense:Math.abs(txs.filter(x=>x.kind==="expense").reduce((s,x)=>s+x.amount,0))}),[txs]);
 const toast=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(""),2800)};
 function add(){const n=Math.abs(Number(draft.amount.replace(/,/g,"")));if(!draft.title||!n)return toast("กรุณากรอกชื่อรายการและจำนวนเงิน");setTxs(v=>[{id:Date.now(),title:draft.title,category:draft.category,date:"วันนี้",amount:draft.kind==="income"?n:-n,kind:draft.kind},...v]);setModal(null);setDraft({title:"",amount:"",kind:"expense",category:"อาหาร"});toast("บันทึกรายการแล้ว")}
 const categoryFor=(s:string)=>/food|restaurant|cafe|อาหาร|กาแฟ|mart/i.test(s)?"อาหาร":/fuel|grab|bolt|bts|mrt|น้ำมัน|เดินทาง/i.test(s)?"เดินทาง":/rent|ค่าเช่า|condo|บ้าน/i.test(s)?"ที่อยู่อาศัย":/salary|payroll|เงินเดือน/i.test(s)?"รายรับ":"อื่น ๆ";
 async function loadStatement(file?:File){if(!file)return;setProcessing(true);setProgress(18);try{const XLSX=await import("xlsx");setProgress(42);const data=await file.arrayBuffer();const book=XLSX.read(data,{type:"array",cellDates:true});const sheet=book.Sheets[book.SheetNames[0]];const raw=XLSX.utils.sheet_to_json<(string|number)[]>(sheet,{header:1,defval:""});setProgress(68);const rows=raw.filter(r=>r.some(Boolean));const header=rows[0]?.map(x=>String(x).toLowerCase())||[];const find=(words:string[])=>header.findIndex(h=>words.some(w=>h.includes(w)));const dateI=find(["date","วันที่"]),titleI=find(["description","detail","รายการ","คำอธิบาย"]),amountI=find(["amount","ยอดเงิน","จำนวน"]),debitI=find(["debit","ถอน","จ่าย"]),creditI=find(["credit","ฝาก","รับ"]);const items:Tx[]=rows.slice(1).map((r,i)=>{const title=String(r[titleI>=0?titleI:1]||"รายการนำเข้า");const credit=creditI>=0?Number(String(r[creditI]).replace(/,/g,"")):0;const debit=debitI>=0?Number(String(r[debitI]).replace(/,/g,"")):0;const rawAmount=amountI>=0?Number(String(r[amountI]).replace(/,/g,"")):credit-debit;const kind:Tx["kind"]=credit>0||rawAmount>0?"income":"expense";const n=Math.abs(rawAmount||debit||credit);return{id:Date.now()+i,title,category:categoryFor(title),date:String(r[dateI>=0?dateI:0]||"ไม่ระบุวันที่"),amount:kind==="income"?n:-n,kind}}).filter(x=>x.amount!==0);const keys=new Set(txs.map(x=>`${x.date}|${x.title}|${x.amount}`)),unique=items.filter(x=>!keys.has(`${x.date}|${x.title}|${x.amount}`));setTxs(v=>[...unique,...v]);setProgress(100);setSummary({files:1,rows:unique.length,income:unique.filter(x=>x.kind==="income").reduce((s,x)=>s+x.amount,0),expense:Math.abs(unique.filter(x=>x.kind==="expense").reduce((s,x)=>s+x.amount,0)),duplicates:items.length-unique.length,source:file.name});setModal("summary")}catch{toast("อ่านไฟล์ไม่สำเร็จ กรุณาตรวจรูปแบบคอลัมน์")}finally{setProcessing(false)}}
 async function loadReceipt(file?:File){if(!file)return;setProcessing(true);setProgress(8);try{const {recognize}=await import("tesseract.js");const result=await recognize(file,"eng+tha",{logger:m=>{if(m.status==="recognizing text")setProgress(Math.round(m.progress*90))}});const text=result.data.text;const amounts=[...text.matchAll(/(?:THB|บาท|฿)?\s*([0-9]{1,3}(?:,[0-9]{3})*(?:\.\d{2}))/gi)].map(m=>Number(m[1].replace(/,/g,""))).filter(n=>n>0);const amount=amounts.sort((a,b)=>b-a)[0]||0;const title=(text.split(/\r?\n/).map(x=>x.trim()).find(x=>x.length>3&&!/[0-9]/.test(x))||file.name.replace(/\.[^.]+$/,"")).slice(0,60);setDraft({title,amount:amount?String(amount):"",kind:"expense",category:categoryFor(text)});setModal("add");toast(amount?"อ่านข้อความแล้ว กรุณาตรวจสอบก่อนบันทึก":"อ่านสลิปแล้ว กรุณาเติมยอดเงินก่อนบันทึก")}catch{toast("อ่านข้อความไม่สำเร็จ กรุณากรอกข้อมูลด้วยตนเอง");setModal("add")}finally{setProcessing(false);setProgress(100)}}
 return <main className="min-h-screen bg-[#f3f6f5] text-[#17211e]">
  <aside className={`fixed inset-y-0 left-0 z-40 w-[252px] border-r border-[#dfe6e2] bg-[#f9fbfa] px-4 py-5 transition-transform lg:translate-x-0 ${drawer?"translate-x-0":"-translate-x-full"}`}>
   <div className="mb-8 flex items-center justify-between px-2"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#123f36] text-white"><CircleDollarSign size={22}/></span><div><strong className="block text-[17px]">เงินดี</strong><span className="text-xs text-[#70807a]">บัญชีส่วนตัว</span></div></div><button className="lg:hidden" onClick={()=>setDrawer(false)} aria-label="ปิดเมนู"><X/></button></div>
   <nav className="space-y-1">{nav.map(([Icon,label])=><button key={label} onClick={()=>{setActive(label);setDrawer(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-[15px] font-medium ${active===label?"bg-[#dcebe5] text-[#123f36]":"text-[#596762] hover:bg-[#edf2f0]"}`}><Icon size={19}/>{label}</button>)}</nav>
   <div className="absolute bottom-5 left-4 right-4"><button onClick={()=>{setActive("ตั้งค่า");setDrawer(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 ${active==="ตั้งค่า"?"bg-[#dcebe5] text-[#123f36]":"text-[#596762]"}`}><Settings size={19}/>ตั้งค่า</button><div className="mt-3 flex items-center gap-3 rounded-2xl border border-[#dfe6e2] bg-white p-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-[#f2bf5e] font-bold">ฉ</span><div className="flex-1"><b className="block text-sm">บัญชีของฉัน</b><span className="text-xs text-[#70807a]">ซิงก์แล้ว</span></div><MoreHorizontal size={18}/></div></div>
  </aside>
  <section className="lg:pl-[252px]">
   <header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-[#dfe6e2] bg-[#f9fbfa]/90 px-4 backdrop-blur-xl sm:px-7"><div className="flex items-center gap-3"><button onClick={()=>setDrawer(true)} className="rounded-lg p-2 lg:hidden"><Menu/></button><div><h1 className="text-lg font-bold sm:text-xl">{active}</h1><p className="hidden text-xs text-[#71807b] sm:block">ข้อมูลล่าสุด ณ 15 กันยายน 2569</p></div></div><div className="flex gap-2"><button className="rounded-xl border border-[#dfe6e2] bg-white p-2.5"><Search size={19}/></button><button className="rounded-xl border border-[#dfe6e2] bg-white p-2.5"><Bell size={19}/></button><button onClick={()=>setModal("add")} className="ml-1 flex items-center gap-2 rounded-xl bg-[#123f36] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={18}/><span className="hidden sm:inline">เพิ่มรายการ</span></button></div></header>
   <div className="mx-auto max-w-[1320px] p-4 sm:p-7">
    {active==="ภาพรวม"?<>
    <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-[#6b7a75]">เงินคงเหลือทั้งหมด</p><h2 className="mt-1 text-3xl font-bold sm:text-4xl">฿128,450</h2><p className="mt-2 text-sm font-medium text-[#2d8267]">↑ 8.2% จากเดือนที่แล้ว</p></div><button className="rounded-xl border border-[#d9e1de] bg-white px-3 py-2 text-sm">กันยายน 2569</button></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<ArrowDownLeft/>} label="รายรับเดือนนี้" value={baht(totals.income)} note="เป้าหมาย ฿60,000" tone="green"/><Stat icon={<ArrowUpRight/>} label="รายจ่ายเดือนนี้" value={baht(totals.expense)} note="ใช้ไป 54% ของงบ" tone="orange"/><Stat icon={<PiggyBank/>} label="เงินออม" value="฿24,000" note="40% ของรายรับ" tone="blue"/><Stat icon={<TrendingUp/>} label="พอร์ตลงทุน" value="฿342,800" note="+฿6,420 เดือนนี้" tone="violet"/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]"><div className="rounded-2xl border border-[#dfe6e2] bg-white p-5 sm:p-6"><h3 className="font-bold">กระแสเงินสด</h3><p className="text-sm text-[#73817c]">รายรับและรายจ่าย 6 เดือนล่าสุด</p><Chart/></div><div className="rounded-2xl border border-[#dfe6e2] bg-white p-5 sm:p-6"><div className="flex justify-between"><div><h3 className="font-bold">งบประมาณเดือนนี้</h3><p className="text-sm text-[#73817c]">เหลือใช้ ฿18,480</p></div><b>54%</b></div><div className="mt-5 h-3 rounded-full bg-[#e8eeeb]"><div className="h-full w-[54%] rounded-full bg-[#d78952]"/></div><div className="mt-6 space-y-4"><Budget name="อาหาร" used="฿8,160" total="฿12,000" p={68}/><Budget name="เดินทาง" used="฿3,240" total="฿6,000" p={54}/><Budget name="ช้อปปิ้ง" used="฿4,120" total="฿8,000" p={52}/><Budget name="บันเทิง" used="฿2,000" total="฿5,000" p={40}/></div></div></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.65fr_1fr]"><div className="overflow-hidden rounded-2xl border border-[#dfe6e2] bg-white"><div className="p-5 sm:px-6"><h3 className="font-bold">รายการล่าสุด</h3><p className="text-sm text-[#73817c]">การเคลื่อนไหวทุกบัญชี</p></div><div className="divide-y divide-[#edf1ef]">{txs.slice(0,5).map(t=><div key={t.id} className="flex items-center gap-3 px-5 py-3.5 sm:px-6"><span className={`grid h-10 w-10 place-items-center rounded-xl ${t.kind==="income"?"bg-[#def1e9] text-[#26735c]":"bg-[#f5ece5] text-[#a45d35]"}`}>{t.kind==="income"?<ArrowDownLeft size={19}/>:<ReceiptText size={19}/>}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{t.title}</b><span className="text-xs text-[#75827e]">{t.category} · {t.date}</span></div><b className={t.kind==="income"?"text-[#26735c]":""}>{t.amount>0?"+":"−"}{baht(t.amount)}</b></div>)}</div></div>
     <div className="rounded-2xl bg-[#123f36] p-5 text-white sm:p-6"><p className="text-sm text-[#bcd1ca]">ทางลัด</p><h3 className="mt-1 text-xl font-bold">เพิ่มข้อมูลอย่างรวดเร็ว</h3><div className="mt-5 grid grid-cols-2 gap-3"><Quick icon={<Camera/>} label="สแกนสลิป" click={()=>setModal("receipt")}/><Quick icon={<FileSpreadsheet/>} label="นำเข้าไฟล์" click={()=>setModal("import")}/><Quick icon={<CreditCard/>} label="เพิ่มหนี้"/><Quick icon={<Goal/>} label="ตั้งงบ"/></div><div className="mt-5 rounded-xl bg-white/10 p-3 text-xs leading-5 text-[#d9e8e3]">รูปสลิปจะถูกอ่านบนอุปกรณ์ และส่งขึ้นระบบเฉพาะข้อมูลที่คุณกดยืนยัน</div></div>
    </div>
    </>:<ModuleView active={active} txs={txs} openAdd={()=>setModal("add")} openImport={()=>setModal("import")} notify={toast}/>}
   </div>
  </section>
  {modal&&<div className="fixed inset-0 z-50 grid place-items-end bg-[#07130f]/45 sm:place-items-center sm:p-4" onMouseDown={()=>setModal(null)}><div className="w-full max-w-lg rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-6 flex justify-between"><div><h3 className="text-xl font-bold">{modal==="add"?"เพิ่มรายการเงิน":modal==="import"?"นำเข้า Statement":modal==="summary"?"สรุปทันที":"อ่านรูปสลิป"}</h3><p className="mt-1 text-sm text-[#71807b]">{modal==="receipt"?"ประมวลผลภายในเครื่องของคุณ":modal==="summary"?summary.source:"ตรวจสอบข้อมูลก่อนบันทึกได้เสมอ"}</p></div><button onClick={()=>setModal(null)} className="h-9 rounded-full bg-[#eef2f0] p-2"><X size={19}/></button></div>
   {modal==="add"&&<div className="space-y-4"><div className="grid grid-cols-2 gap-2 rounded-xl bg-[#edf2f0] p-1"><button onClick={()=>setDraft({...draft,kind:"expense"})} className={`rounded-lg py-2 text-sm font-semibold ${draft.kind==="expense"?"bg-white shadow-sm":""}`}>รายจ่าย</button><button onClick={()=>setDraft({...draft,kind:"income"})} className={`rounded-lg py-2 text-sm font-semibold ${draft.kind==="income"?"bg-white shadow-sm":""}`}>รายรับ</button></div><Field label="ชื่อรายการ"><input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="เช่น ค่าอาหารกลางวัน"/></Field><Field label="จำนวนเงิน"><input value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})} inputMode="decimal" placeholder="0.00"/></Field><Field label="หมวดหมู่"><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{["อาหาร","เดินทาง","ที่อยู่อาศัย","ช้อปปิ้ง","สุขภาพ","การลงทุน","รายรับ","อื่น ๆ"].map(x=><option key={x}>{x}</option>)}</select></Field><button onClick={add} className="w-full rounded-xl bg-[#123f36] py-3 font-bold text-white">บันทึกรายการ</button></div>}
   {modal==="import"&&<div><input ref={csv} className="hidden" type="file" accept=".xlsx,.xls,.csv,.tsv" onChange={e=>loadStatement(e.target.files?.[0])}/><button onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();loadStatement(e.dataTransfer.files[0])}} onClick={()=>csv.current?.click()} className="grid w-full place-items-center rounded-2xl border-2 border-dashed border-[#b9cac4] px-5 py-12"><FileSpreadsheet className="mb-3 text-[#256c59]" size={36}/><b>เลือกหรือลากไฟล์ Statement</b><span className="mt-1 text-sm text-[#71807b]">รองรับ Excel, CSV และ TSV</span></button><div className="mt-4 flex gap-2 rounded-xl bg-[#eef5f2] p-3 text-xs text-[#486159]"><CheckCircle2 size={18}/><span>ระบบค้นหาคอลัมน์วันที่ รายการ เงินเข้า และเงินออกให้อัตโนมัติ พร้อมป้องกันรายการซ้ำ</span></div></div>}
   {modal==="receipt"&&<div><input ref={receipt} className="hidden" type="file" accept="image/*" capture="environment" onChange={e=>loadReceipt(e.target.files?.[0])}/><button onClick={()=>receipt.current?.click()} className="grid w-full place-items-center rounded-2xl border-2 border-dashed border-[#b9cac4] px-5 py-12"><Camera className="mb-3 text-[#256c59]" size={36}/><b>ถ่ายภาพหรือเลือกรูปสลิป</b><span className="mt-1 text-sm text-[#71807b]">รองรับ JPG, PNG และ HEIC</span></button><div className="mt-4 rounded-xl bg-[#eef5f2] p-3 text-xs text-[#486159]">ระบบจะไม่ส่งภาพนี้ไปยังบริการ AI ภายนอก</div></div>}
   {modal==="summary"&&<div><div className="grid grid-cols-2 gap-3"><SummaryCard label="รายการใหม่" value={String(summary.rows)}/><SummaryCard label="ไฟล์ที่อ่าน" value={String(summary.files)}/><SummaryCard label="เงินเข้า" value={baht(summary.income)} green/><SummaryCard label="เงินออก" value={baht(summary.expense)}/></div>{summary.duplicates>0&&<div className="mt-4 flex gap-2 rounded-xl bg-[#fff4df] p-3 text-sm text-[#7b571c]"><AlertTriangle size={19}/><span>ข้ามรายการซ้ำ {summary.duplicates} รายการ</span></div>}<button onClick={()=>setModal(null)} className="mt-5 w-full rounded-xl bg-[#123f36] py-3 font-bold text-white">ดูรายการบนแดชบอร์ด</button></div>}
  </div></div>}
  {processing&&<div className="fixed inset-0 z-[70] grid place-items-center bg-[#07130f]/55 p-5"><div className="w-full max-w-sm rounded-3xl bg-white p-6 text-center shadow-2xl"><LoaderCircle className="mx-auto animate-spin text-[#256c59]" size={38}/><h3 className="mt-4 text-lg font-bold">กำลังสรุปข้อมูลแบบเรียลไทม์</h3><p className="mt-1 text-sm text-[#71807b]">กรุณาอย่าปิดหน้าต่างนี้</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[#e5ece9]"><div className="h-full rounded-full bg-[#2b765f] transition-all" style={{width:`${progress}%`}}/></div><b className="mt-2 block text-sm">{progress}%</b></div></div>}
  {notice&&<div className="fixed bottom-5 left-1/2 z-[60] -translate-x-1/2 rounded-xl bg-[#17211e] px-4 py-3 text-sm text-white shadow-xl">{notice}</div>}
 </main>
}
function Stat({icon,label,value,note,tone}:{icon:React.ReactNode;label:string;value:string;note:string;tone:string}){const c:Record<string,string>={green:"bg-[#def1e9] text-[#26735c]",orange:"bg-[#f5e9df] text-[#a45d35]",blue:"bg-[#e2edf4] text-[#3e6f8d]",violet:"bg-[#ece7f5] text-[#705b99]"};return <div className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><div className="flex justify-between"><span className={`grid h-10 w-10 place-items-center rounded-xl ${c[tone]}`}>{icon}</span><MoreHorizontal size={18}/></div><p className="mt-5 text-sm text-[#6f7e79]">{label}</p><b className="mt-1 block text-2xl">{value}</b><p className="mt-2 text-xs text-[#7d8985]">{note}</p></div>}
function Budget({name,used,total,p}:{name:string;used:string;total:string;p:number}){return <div><div className="mb-1.5 flex justify-between text-sm"><b>{name}</b><span>{used} / {total}</span></div><div className="h-1.5 rounded-full bg-[#e7ecea]"><div className="h-full rounded-full bg-[#2b765f]" style={{width:`${p}%`}}/></div></div>}
function Quick({icon,label,click}:{icon:React.ReactNode;label:string;click?:()=>void}){return <button onClick={click} className="rounded-xl bg-white/10 p-4 text-left hover:bg-white/15"><span className="mb-3 block text-[#b9d7cd]">{icon}</span><b className="text-sm">{label}</b></button>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-semibold">{label}<div className="mt-1.5 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-[#d7e0dc] [&>*]:px-3 [&>*]:py-3">{children}</div></label>}
function SummaryCard({label,value,green}:{label:string;value:string;green?:boolean}){return <div className="rounded-2xl border border-[#dfe6e2] bg-[#f8faf9] p-4"><span className="text-xs text-[#71807b]">{label}</span><b className={`mt-1 block text-xl ${green?"text-[#26735c]":""}`}>{value}</b></div>}
function Chart(){const inc=[44,51,47,56,49,58],exp=[31,35,38,34,41,32];return <div className="mt-4 h-[220px]"><div className="flex h-[180px] items-end justify-between gap-3 border-b border-[#dfe6e2]">{inc.map((v,i)=><div key={i} className="flex h-full flex-1 items-end justify-center gap-1"><div className="w-[34%] rounded-t-md bg-[#2b765f]" style={{height:`${v*2.5}px`}}/><div className="w-[34%] rounded-t-md bg-[#d9a06f]" style={{height:`${exp[i]*2.5}px`}}/></div>)}</div><div className="mt-3 flex justify-between text-xs text-[#7a8782]">{["เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย."].map(x=><span key={x}>{x}</span>)}</div></div>}
