"use client";
import { CreditCard } from "lucide-react";
import type { Tx } from "@/app/page";

const baht=(n:number)=>new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",maximumFractionDigits:0}).format(Math.abs(n));
type Props={active:string;txs:Tx[];openAdd:()=>void;openImport:()=>void;notify:(s:string)=>void};

export default function ModuleView({active,txs,openAdd,openImport,notify}:Props){
 void notify;
 if(active==="รายการเงิน")return <><Head title="รายการเงินทั้งหมด" text="ค้นหา ตรวจสอบ และจัดหมวดหมู่รายการจากทุกบัญชี"><Action label="นำเข้า Statement" onClick={openImport}/><Action label="เพิ่มรายการ" onClick={openAdd}/></Head><div className="mb-4 grid gap-3 sm:grid-cols-3"><Mini label="รายการทั้งหมด" value={String(txs.length)}/><Mini label="เงินเข้า" value={baht(txs.filter(x=>x.kind==="income").reduce((s,x)=>s+x.amount,0))} good/><Mini label="เงินออก" value={baht(txs.filter(x=>x.kind==="expense").reduce((s,x)=>s+x.amount,0))}/></div><Panel title="ประวัติรายการ" sub="เรียงจากรายการล่าสุด"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b text-[#71807b]"><tr><th className="py-3">วันที่</th><th>รายการ</th><th>หมวดหมู่</th><th>ประเภท</th><th className="text-right">จำนวนเงิน</th></tr></thead><tbody>{txs.map(t=><tr key={t.id} className="border-b border-[#edf1ef]"><td className="py-4">{t.date}</td><td className="font-semibold">{t.title}</td><td><Tag>{t.category}</Tag></td><td>{t.kind==="income"?"รายรับ":"รายจ่าย"}</td><td className={`text-right font-bold ${t.kind==="income"?"text-[#26735c]":""}`}>{t.amount>0?"+":"−"}{baht(t.amount)}</td></tr>)}</tbody></table></div></Panel></>;
 if(active==="บัญชี")return <><Head title="บัญชีและเงินสด" text="ยอดคงเหลือจากทุกบัญชี อัปเดตหลังนำเข้า Statement"><Action label="เพิ่มบัญชี"/></Head><div className="grid gap-4 lg:grid-cols-3"><Account name="บัญชีใช้จ่าย" bank="กสิกรไทย · •• 4281" amount="฿62,450" color="bg-[#123f36] text-white"/><Account name="บัญชีเงินออม" bank="ไทยพาณิชย์ · •• 8036" amount="฿54,000" color="bg-[#e7bd68] text-[#3f2d0a]"/><Account name="เงินสด" bank="ปรับยอดล่าสุดวันนี้" amount="฿12,000" color="bg-[#6d96aa] text-white"/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Panel title="สัดส่วนเงินของคุณ" sub="รวมทั้งหมด ฿128,450"><Bar/><div className="mt-5 grid grid-cols-3 gap-2 text-xs"><Key c="#164a3e" t="ใช้จ่าย 49%"/><Key c="#dcae54" t="ออม 42%"/><Key c="#5f8fa7" t="เงินสด 9%"/></div></Panel><Panel title="อัปเดตยอดบัญชี" sub="นำเข้าไฟล์แทนการเชื่อมธนาคารโดยตรง"><Status name="กสิกรไทย" date="วันนี้ 19:42"/><Status name="ไทยพาณิชย์" date="14 ก.ย. 2569"/><div className="mt-4"><Action label="อัปเดตด้วย Statement" onClick={openImport}/></div></Panel></div></>;
 if(active==="บัตรและหนี้")return <><Head title="บัตรเครดิตและหนี้" text="ติดตามยอดค้าง วันครบกำหนด และแผนชำระ"><Action label="เพิ่มบัตรหรือหนี้"/></Head><Stats data={[["หนี้คงเหลือ","฿186,500"],["ต้องจ่ายเดือนนี้","฿18,750"],["วงเงินคงเหลือ","฿74,200"]]}/><div className="mt-5 grid gap-5 lg:grid-cols-2"><Debt name="KBank Platinum" type="บัตรเครดิต · •• 4821" due="ครบกำหนด 28 ก.ย." amount="฿12,350" p={42}/><Debt name="สินเชื่อรถยนต์" type="เหลือ 26 งวด" due="ครบกำหนด 5 ต.ค." amount="฿174,150" p={63}/></div><div className="mt-5"><Panel title="แผนชำระเดือนนี้" sub="เรียงตามวันครบกำหนด"><Rows rows={[["28 ก.ย.","KBank Platinum","฿12,350"],["5 ต.ค.","สินเชื่อรถยนต์","฿6,400"]]}/></Panel></div></>;
 if(active==="งบประมาณ")return <><Head title="งบประมาณเดือนกันยายน" text="กำหนดเพดานรายจ่ายและติดตามแบบเรียลไทม์"><Action label="สร้างงบใหม่"/></Head><Stats data={[["งบทั้งหมด","฿34,000"],["ใช้ไปแล้ว","฿17,520"],["คงเหลือ","฿16,480"]]}/><div className="mt-5"><Panel title="งบตามหมวดหมู่" sub="อัปเดตจากรายการเงินอัตโนมัติ"><div className="mt-5 space-y-6">{[["อาหาร","฿8,160","฿12,000",68],["เดินทาง","฿3,240","฿6,000",54],["ช้อปปิ้ง","฿4,120","฿8,000",52],["บันเทิง","฿2,000","฿5,000",40],["สุขภาพ","฿0","฿3,000",0]].map(x=><BudgetRow key={String(x[0])} x={x}/>)}</div></Panel></div></>;
 if(active==="เงินออม")return <><Head title="เป้าหมายเงินออม" text="แบ่งเงินออมตามเป้าหมายและติดตามความคืบหน้า"><Action label="เพิ่มเป้าหมาย"/></Head><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><GoalCard name="เงินสำรองฉุกเฉิน" saved="฿120,000" target="฿180,000" p={67}/><GoalCard name="ท่องเที่ยวญี่ปุ่น" saved="฿42,000" target="฿80,000" p={53}/><GoalCard name="ดาวน์บ้าน" saved="฿310,000" target="฿800,000" p={39}/></div><div className="mt-5"><Panel title="แผนออมอัตโนมัติ" sub="ยอดที่ควรแยกเก็บทุกเดือน"><Rows rows={[["ทุกวันที่ 16","เงินสำรองฉุกเฉิน","฿10,000"],["ทุกวันที่ 16","ท่องเที่ยวญี่ปุ่น","฿6,500"],["ทุกวันที่ 1","ดาวน์บ้าน","฿15,000"]]}/></Panel></div></>;
 if(active==="การลงทุน")return <><Head title="พอร์ตการลงทุน" text="ภาพรวมสินทรัพย์ ต้นทุน และผลตอบแทน"><Action label="เพิ่มสินทรัพย์"/></Head><Stats data={[["มูลค่าพอร์ต","฿342,800"],["กำไรทั้งหมด","+฿28,420"],["ผลตอบแทน","+9.04%"]]}/><div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Panel title="สินทรัพย์ในพอร์ต" sub="ราคาที่บันทึกล่าสุด"><Rows rows={[["กองทุน","K-USXNDQ-A(A)","฿142,600"],["หุ้นไทย","CPALL","฿74,500"],["ทองคำ","Gold Spot","฿82,300"],["คริปโท","BTC","฿43,400"]]}/></Panel><Panel title="การกระจายสินทรัพย์" sub="ตามมูลค่าปัจจุบัน"><Donut/><div className="grid grid-cols-2 gap-3 text-sm"><Key c="#164a3e" t="กองทุน 42%"/><Key c="#dcae54" t="หุ้น 22%"/><Key c="#5f8fa7" t="ทอง 24%"/><Key c="#8668a0" t="คริปโท 12%"/></div></Panel></div></>;
 if(active==="ภาษี")return <><Head title="วางแผนภาษีปี 2569" text="ประมาณการจากข้อมูลที่บันทึกเพื่อช่วยวางแผน"><Action label="เพิ่มค่าลดหย่อน"/></Head><Stats data={[["รายได้สะสม","฿696,000"],["ค่าลดหย่อน","฿160,000"],["ภาษีประมาณการ","฿21,700"]]}/><div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_1fr]"><Panel title="รายการลดหย่อน" sub="ตรวจเอกสารก่อนยื่นจริง"><Rows rows={[["ส่วนตัว","ค่าลดหย่อนส่วนตัว","฿60,000"],["ประกัน","ประกันสังคม","฿9,000"],["ลงทุน","กองทุน RMF","฿60,000"],["บริจาค","เงินบริจาคทั่วไป","฿31,000"]]}/></Panel><Panel title="เอกสารที่ต้องเตรียม" sub="ทำเครื่องหมายเมื่อพร้อม"><Checklist/></Panel></div><div className="mt-4 rounded-xl bg-[#fff4df] p-4 text-sm text-[#6f521f]">ตัวเลขเป็นการประมาณการ ควรตรวจสอบกับเอกสารจริงหรือผู้เชี่ยวชาญก่อนยื่นภาษี</div></>;
 return <><Head title="ตั้งค่าระบบ" text="จัดการโปรไฟล์ ความปลอดภัย การซิงก์ และรูปแบบข้อมูล"/><div className="grid gap-5 lg:grid-cols-2"><Panel title="บัญชีผู้ใช้" sub="ข้อมูลส่วนตัวและการเข้าสู่ระบบ"><Setting n="ชื่อบัญชี" v="บัญชีของฉัน"/><Setting n="สกุลเงินหลัก" v="บาทไทย (THB)"/><Setting n="ภาษา" v="ไทย"/></Panel><Panel title="ความเป็นส่วนตัว" sub="การประมวลผลข้อมูลการเงิน"><Setting n="อ่านสลิป" v="ภายในอุปกรณ์"/><Setting n="ซิงก์ข้อมูล" v="เปิดใช้งาน"/><Setting n="ล็อกอัตโนมัติ" v="หลัง 5 นาที"/></Panel></div></>;
}
function Action({label,onClick}:{label:string;onClick?:()=>void}){return <button onClick={onClick} className="rounded-xl bg-[#123f36] px-4 py-2.5 text-sm font-semibold text-white">{label}</button>}
function Head({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-bold">{title}</h2><p className="mt-1 text-sm text-[#71807b]">{text}</p></div><div className="flex gap-2">{children}</div></div>}
function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <div className="rounded-2xl border border-[#dfe6e2] bg-white p-5 sm:p-6"><h3 className="font-bold">{title}</h3><p className="text-sm text-[#71807b]">{sub}</p>{children}</div>}
function Mini({label,value,good}:{label:string;value:string;good?:boolean}){return <div className="rounded-2xl border border-[#dfe6e2] bg-white p-5"><span className="text-sm text-[#71807b]">{label}</span><b className={`mt-2 block text-2xl ${good?"text-[#26735c]":""}`}>{value}</b></div>}
function Stats({data}:{data:string[][]}){return <div className="grid gap-3 sm:grid-cols-3">{data.map((x,i)=><Mini key={x[0]} label={x[0]} value={x[1]} good={i===2}/>)}</div>}
function Tag({children}:{children:React.ReactNode}){return <span className="rounded-full bg-[#edf3f0] px-2.5 py-1 text-xs">{children}</span>}
function Account({name,bank,amount,color}:{name:string;bank:string;amount:string;color:string}){return <div className={`rounded-2xl p-5 ${color}`}><CreditCard/><p className="mt-7 text-sm opacity-75">{bank}</p><h3 className="mt-1 font-bold">{name}</h3><b className="mt-3 block text-2xl">{amount}</b></div>}
function Bar(){return <div className="mt-6 flex h-4 overflow-hidden rounded-full"><span className="w-[49%] bg-[#164a3e]"/><span className="w-[42%] bg-[#dcae54]"/><span className="w-[9%] bg-[#5f8fa7]"/></div>}
function Key({c,t}:{c:string;t:string}){return <div className="flex items-center gap-2"><span className="h-3 w-3 rounded-full" style={{background:c}}/>{t}</div>}
function Status({name,date}:{name:string;date:string}){return <div className="mt-3 flex items-center justify-between rounded-xl bg-[#f4f7f5] p-3"><div><b className="text-sm">{name}</b><p className="text-xs text-[#71807b]">{date}</p></div><span className="h-2.5 w-2.5 rounded-full bg-[#3b9b79]"/></div>}
function Debt({name,type,due,amount,p}:{name:string;type:string;due:string;amount:string;p:number}){return <Panel title={name} sub={type}><div className="mt-5 flex justify-between text-sm"><span>{due}</span><b>{amount}</b></div><Progress p={p}/><button className="mt-4 text-sm font-bold text-[#1c6655]">ดูรายละเอียดและชำระ</button></Panel>}
function GoalCard({name,saved,target,p}:{name:string;saved:string;target:string;p:number}){return <Panel title={name} sub={`เป้าหมาย ${target}`}><b className="mt-5 block text-2xl">{saved}</b><Progress p={p}/><p className="mt-2 text-right text-xs font-bold">{p}%</p></Panel>}
function Progress({p}:{p:number}){return <div className="mt-4 h-2 rounded-full bg-[#e7ecea]"><div className="h-full rounded-full bg-[#2b765f]" style={{width:`${p}%`}}/></div>}
function BudgetRow({x}:{x:(string|number)[]}){return <div><div className="mb-2 flex justify-between text-sm"><b>{x[0]}</b><span>{x[1]} / {x[2]}</span></div><Progress p={Number(x[3])}/></div>}
function Rows({rows}:{rows:string[][]}){return <div className="mt-4 divide-y divide-[#edf1ef]">{rows.map((r,i)=><div key={i} className="grid grid-cols-[90px_1fr_auto] gap-3 py-4 text-sm"><span className="text-[#71807b]">{r[0]}</span><b>{r[1]}</b><b>{r[2]}</b></div>)}</div>}
function Donut(){return <div className="mx-auto my-5 grid h-40 w-40 place-items-center rounded-full" style={{background:"conic-gradient(#164a3e 0 42%,#dcae54 42% 64%,#5f8fa7 64% 88%,#8668a0 88%)"}}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center text-xs">ทั้งหมด<br/><b className="text-base">฿342K</b></div></div>}
function Checklist(){return <div className="mt-4 space-y-3">{["หนังสือรับรอง 50 ทวิ","ใบรับรอง RMF/SSF","หนังสือรับรองดอกเบี้ยบ้าน","ใบเสร็จเงินบริจาค"].map((x,i)=><label key={x} className="flex items-center gap-3 rounded-xl bg-[#f4f7f5] p-3 text-sm"><input type="checkbox" defaultChecked={i<2} className="h-4 w-4 accent-[#1c6655]"/>{x}</label>)}</div>}
function Setting({n,v}:{n:string;v:string}){return <button className="mt-3 flex w-full justify-between rounded-xl bg-[#f4f7f5] p-4 text-left text-sm"><b>{n}</b><span className="text-[#71807b]">{v} ›</span></button>}
